<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard_flex items-center px-3 py-2 tex_fc9ac5</name>
   <tag></tag>
   <elementGuidId>73b0db69-504b-4640-8b19-f3a04f03a16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/aside/div/div[2]/nav/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Eventos&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62e89166-a745-44f0-9d48-764359a52678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10</value>
      <webElementGuid>6c52a2f5-0930-439a-98e1-b81ebe67aa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/events</value>
      <webElementGuid>df4e414e-7ec3-42d9-bb5d-b8df8f6a1c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eventos</value>
      <webElementGuid>f4eb33f1-e73d-4d0b-9d34-3b5c38b6fdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/aside[@class=&quot;hidden md:flex md:flex-shrink-0 w-64 flex-col border-r border-white/10 relative z-10&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 px-2 py-4 space-y-2&quot;]/a[@class=&quot;flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10&quot;]</value>
      <webElementGuid>d8509cec-6179-49fa-aee6-1a770da5d2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/div/div[2]/nav/a[2]</value>
      <webElementGuid>3422c9c8-0fd4-421c-b931-fb11fbfce879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eventos')]</value>
      <webElementGuid>5facb347-63e6-4ad1-a410-abad6fad6ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>7da823b4-960a-4947-ab2c-4f214a5c2623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mesapra2'])[2]/following::a[2]</value>
      <webElementGuid>8c1af52e-bda7-440f-9726-8dae77dd7922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meus Eventos'])[1]/preceding::a[1]</value>
      <webElementGuid>b33cc47a-9122-427c-8497-5ff999506417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/preceding::a[2]</value>
      <webElementGuid>41cc9699-4799-4d3d-9a6f-09d558868d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eventos']/parent::*</value>
      <webElementGuid>1d460e03-88c8-4392-b1c1-29548eb5ff04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/events')]</value>
      <webElementGuid>8513ff1d-d680-481f-a1d4-6fa2ae67ffc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>b01c2e62-a0ce-42a1-be22-145e3d64013e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/events' and (text() = 'Eventos' or . = 'Eventos')]</value>
      <webElementGuid>e2093b1d-f3cb-42ab-9d24-238eb72dcff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
