<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mesapra2_flex items-center px-3 py-2 text_add56d</name>
   <tag></tag>
   <elementGuidId>fa4259f1-936d-4067-8ae1-a23c5d834ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/aside/div/div[2]/nav/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6c6fe41-fafb-49f2-bd95-aafdf246b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10</value>
      <webElementGuid>d8901b1a-c7c0-4344-bc83-970eac76df05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard</value>
      <webElementGuid>38b9f4b9-566f-4a8f-9300-b639b8281b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>5a75d343-0bd9-43ab-b769-440515dd51a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/aside[@class=&quot;hidden md:flex md:flex-shrink-0 w-64 flex-col border-r border-white/10 relative z-10&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 px-2 py-4 space-y-2&quot;]/a[@class=&quot;flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10&quot;]</value>
      <webElementGuid>8a74d072-552d-470d-9602-0348aa3f7822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/div/div[2]/nav/a</value>
      <webElementGuid>4c97e3c6-5091-422d-8e5e-22b5f71b85d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>2ff23794-9820-47f4-bd82-3c4c50fcf563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mesapra2'])[2]/following::a[1]</value>
      <webElementGuid>1e9cc591-2678-4ebd-97d8-625046e23114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eventos'])[1]/preceding::a[1]</value>
      <webElementGuid>4b92ddc3-4603-47cb-a399-e013c6fc3e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meus Eventos'])[1]/preceding::a[2]</value>
      <webElementGuid>327e84b9-ef52-4516-bc45-2a5f66352f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>051a1ec7-798d-4272-a23d-dd1706386177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard')]</value>
      <webElementGuid>06c93ea3-5079-4d2c-bd7d-006338d39c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>623617c4-6d70-450e-af24-78ce61b08be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>18b5719f-21ef-4d54-94d7-dc01d85e2f4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
