<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chicago Prime_flex items-center gap-2 mb-1</name>
   <tag></tag>
   <elementGuidId>2d15f9cc-20d7-4a78-92e4-074dfd531f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div/div/form/div[5]/div[3]/div/button[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cinemark Rodrigo Party O melhor cinema de Brasília no Pier21 Pier 21, Setor de clubes Sul Tel: 0800800200&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8767532-831f-4b2f-9811-c47f8c20fdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-2 mb-1</value>
      <webElementGuid>391e45a0-a0bb-4e03-847c-babcc5f7757e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cinemark</value>
      <webElementGuid>298424e5-48a5-462a-be81-069faea7fff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/div[@class=&quot;flex flex-col w-0 flex-1 overflow-hidden&quot;]/main[@class=&quot;flex-1 relative overflow-y-auto focus:outline-none pt-16 z-0&quot;]/div[@class=&quot;container mx-auto px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;max-w-3xl mx-auto py-6 px-4&quot;]/div[@class=&quot;space-y-8&quot;]/form[@class=&quot;glass-effect rounded-2xl p-8 border border-white/10 space-y-6&quot;]/div[@class=&quot;space-y-2&quot;]/div[@class=&quot;glass-effect rounded-lg border border-white/10 max-h-64 overflow-y-auto&quot;]/div[@class=&quot;divide-y divide-white/10&quot;]/button[@class=&quot;w-full text-left p-4 hover:bg-white/5 transition-colors&quot;]/div[@class=&quot;flex items-start gap-3&quot;]/div[@class=&quot;flex-1 min-w-0&quot;]/div[@class=&quot;flex items-center gap-2 mb-1&quot;]</value>
      <webElementGuid>0ef29e3b-915e-4690-8f4f-b2d3b2755349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/form/div[5]/div[3]/div/button[3]/div/div/div</value>
      <webElementGuid>6c647347-2164-46f9-b6ee-916744735fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chicago Prime'])[1]/following::div[4]</value>
      <webElementGuid>9cc83f88-a3fe-4d7a-8a32-845508c3603e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belini'])[1]/following::div[8]</value>
      <webElementGuid>3493d0c9-a71e-46cd-9bff-dbf143cc9ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coco Bambu'])[1]/preceding::div[2]</value>
      <webElementGuid>4bc94420-2f49-46f6-a086-5a57728726d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/div/div/div</value>
      <webElementGuid>632c71d0-620d-4515-a11e-2638c8e14807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cinemark' or . = 'Cinemark')]</value>
      <webElementGuid>dcdbc72b-ec1e-4b52-ab5d-edc8231cd054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
