<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero de Vagas_acceptedTerms</name>
   <tag></tag>
   <elementGuidId>8c9ff7e4-cefb-4a9b-a378-4d079cc90422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptedTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptedTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Concordo com os Termos de Uso e Políticas de Cancelamento *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef8d41d2-4ee1-44f7-8082-9c1444caf18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>22a611f1-3bb5-4d76-a49a-8a1e1cd5275f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptedTerms</value>
      <webElementGuid>dcc7754a-6be8-4898-89c3-b51ba2a9d645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acceptedTerms</value>
      <webElementGuid>cfa26968-b025-43aa-a345-5ea78558c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-5 h-5 mt-0.5 rounded border-white/10 bg-white/5 checked:bg-purple-500</value>
      <webElementGuid>fcb85a42-63eb-494f-ba38-0f0b6dbdd479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptedTerms&quot;)</value>
      <webElementGuid>a1ebef8f-431c-4245-b225-10c6c2365e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptedTerms']</value>
      <webElementGuid>119edeae-1b10-415b-a0e2-e61e7ff5328a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/form/div[9]/div/input</value>
      <webElementGuid>c2fb1a62-6789-46ef-8b77-0b3613445f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>9a2ec265-fff3-414a-8422-d04641aae052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptedTerms' and @name = 'acceptedTerms']</value>
      <webElementGuid>017f2268-3adb-4b93-bc49-06b6124790e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
