<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Restaurantes_flex items-center px-3 py-2 _809843</name>
   <tag></tag>
   <elementGuidId>2bba05f9-691e-4206-afc4-a022f3efb816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/aside/div/div[2]/nav/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Pessoas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c5315dc-ff24-49e4-a3b7-6f3e1ea6bafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10</value>
      <webElementGuid>0aef7d8b-6e10-4a9a-bc7b-99b9c7ececf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/people</value>
      <webElementGuid>a95777e3-1d9d-4d56-af1c-137d14b7a465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pessoas</value>
      <webElementGuid>80e19f69-baba-40e9-b0a4-b25910a89fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/aside[@class=&quot;hidden md:flex md:flex-shrink-0 w-64 flex-col border-r border-white/10 relative z-10&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 px-2 py-4 space-y-2&quot;]/a[@class=&quot;flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10&quot;]</value>
      <webElementGuid>439463ca-3540-4fd7-98bb-b1964aa0615f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/div/div[2]/nav/a[5]</value>
      <webElementGuid>0fab381a-2525-4e9a-8e91-20b528e9f55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pessoas')]</value>
      <webElementGuid>55e620a4-8ed5-4f39-b5d4-d7bbd16581f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/following::a[1]</value>
      <webElementGuid>071778aa-7ce2-46c0-b159-5883220399c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meus Eventos'])[1]/following::a[2]</value>
      <webElementGuid>c221fabf-ee7a-4714-9630-8cf2cbed3a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meu Perfil'])[1]/preceding::a[1]</value>
      <webElementGuid>0ab3052e-89a0-4973-aeff-b90d357f8110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurações'])[1]/preceding::a[2]</value>
      <webElementGuid>3d281904-410d-4810-b80e-b5991f66920d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pessoas']/parent::*</value>
      <webElementGuid>55e683da-d255-4582-a7d6-329ab14d672b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/people')]</value>
      <webElementGuid>c1fb58f7-d957-4ffd-a8c9-c3f41edd8814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>b89a8d14-89f5-40ab-b6f1-b42d7ad97f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/people' and (text() = 'Pessoas' or . = 'Pessoas')]</value>
      <webElementGuid>1d833b19-13c4-4b2b-8dec-434a4eb085f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
