<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Restaurantes_flex items-center px-3 py-2 _809843</name>
   <tag></tag>
   <elementGuidId>dfe9f9dc-c089-4775-9e36-8fbb96c8c33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/aside/div/div[2]/nav/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Pessoas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>793896eb-0a7b-42f9-bdcd-400c1cbde19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10</value>
      <webElementGuid>d2451db8-f8c6-4fe7-a5db-afbe5f189429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/people</value>
      <webElementGuid>6a1ce693-f32b-462f-ab31-aea08e5f7896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pessoas</value>
      <webElementGuid>7d04e5c0-2342-4267-b692-ff55195cd1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/aside[@class=&quot;hidden md:flex md:flex-shrink-0 w-64 flex-col border-r border-white/10 relative z-10&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 px-2 py-4 space-y-2&quot;]/a[@class=&quot;flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10&quot;]</value>
      <webElementGuid>40e5b9dd-6295-4759-8079-7ce84fff5dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/div/div[2]/nav/a[5]</value>
      <webElementGuid>40fa7f56-a378-424b-821b-2a7c9a92f23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pessoas')]</value>
      <webElementGuid>cb989e13-6d06-41f5-8fc7-710c108c4c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/following::a[1]</value>
      <webElementGuid>8bab5bac-432d-4624-9d2b-1a878dff277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meus Eventos'])[1]/following::a[2]</value>
      <webElementGuid>444a0ded-0325-47f7-aac3-3b6154910efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meu Perfil'])[1]/preceding::a[1]</value>
      <webElementGuid>92015b42-be7c-4531-9883-f6ba79c9d79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurações'])[1]/preceding::a[2]</value>
      <webElementGuid>d47a5c11-6b49-4c86-8f9c-7788fee25fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pessoas']/parent::*</value>
      <webElementGuid>ed71c7d7-3e7f-42f6-a05f-5f4ef9c0c7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/people')]</value>
      <webElementGuid>78669329-f479-4b6b-a911-eefd80869033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>60c3b46c-97cf-461b-b5ce-b30b177d328b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/people' and (text() = 'Pessoas' or . = 'Pessoas')]</value>
      <webElementGuid>d98f7a8f-e162-42e3-b2e2-13d87588bf51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
