<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard_flex items-center px-3 py-2 tex_fc9ac5</name>
   <tag></tag>
   <elementGuidId>8230660b-ab70-4b28-a53f-bfc76724d07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/aside/div/div[2]/nav/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Eventos&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30d7f8cb-00b5-4378-853f-5128d11b3ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10</value>
      <webElementGuid>7bde9f5f-2d5a-4285-b1e7-07c3a96124eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/events</value>
      <webElementGuid>d0cf1449-883f-441d-8dbf-8706c26086af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eventos</value>
      <webElementGuid>c814d37f-6202-4c79-ab6d-58543814d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen bg-background text-foreground flex&quot;]/aside[@class=&quot;hidden md:flex md:flex-shrink-0 w-64 flex-col border-r border-white/10 relative z-10&quot;]/div[@class=&quot;flex flex-col h-full&quot;]/div[@class=&quot;flex-1 flex flex-col overflow-y-auto&quot;]/nav[@class=&quot;flex-1 px-2 py-4 space-y-2&quot;]/a[@class=&quot;flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors duration-200 text-white/70 hover:text-white hover:bg-white/10&quot;]</value>
      <webElementGuid>81326d71-5869-47d8-a394-159ed4ae3e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/aside/div/div[2]/nav/a[2]</value>
      <webElementGuid>cb589134-400f-4b00-8b6e-590adade71bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eventos')]</value>
      <webElementGuid>e567e026-1c35-4e13-81a8-97f914ff8369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>75bb98df-bfab-4ede-8294-40afdebcd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mesapra2'])[1]/following::a[2]</value>
      <webElementGuid>2a154f6b-46f0-4442-a061-ced6f1c2cbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meus Eventos'])[1]/preceding::a[1]</value>
      <webElementGuid>c3f17d6b-2580-4abc-bdbe-b635aa223d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restaurantes'])[1]/preceding::a[2]</value>
      <webElementGuid>872d952e-8562-4e63-9505-f1b019d585ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eventos']/parent::*</value>
      <webElementGuid>deaef091-a5f7-4888-9924-fe4160a1ca30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/events')]</value>
      <webElementGuid>2cd62478-30cc-45ed-8973-42089663a20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9629a8cc-11e2-46a1-ba53-d23c5d684b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/events' and (text() = 'Eventos' or . = 'Eventos')]</value>
      <webElementGuid>d79ea136-7e6f-403d-8f07-21bbb6293b33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
